# Generated by Django 5.2.4 on 2025-07-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_prochain_paiement',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='type_facturation',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, default='2025-07-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='2025-07-09', max_length=254),
            preserve_default=False,
        ),
    ]
