# Generated by Django 5.2.4 on 2025-07-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiscribe', '0002_remove_subscription_date_prochain_paiement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
