# Generated by Django 5.0.7 on 2025-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiscribe', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='logo',
            field=models.URLField(blank=True, help_text="URL du logo de l'abonnement (facultatif)", null=True),
        ),
    ]
